Fix more typos
QuiltServerTools/BlockBot pull request #31
Opened 2021-11-09 18:31 UTC by nikijaz

2021-11-10 12:22 UTC, Tom-The-Geek requested changes
Have added a few comments where things can be rephrased as well as just having the typos fixed :)

2021-11-10 12:22 UTC, Tom-The-Geek commented on src/main/resources/blockbot-discord.toml
> +# Comma separated list of role ID's allowed to use /link discord command. Leave empty to allow roles
```suggestion
# Comma separated list of role ID's allowed to use /link discord command. Leave empty to allow all roles
```

2021-11-10 12:22 UTC, Tom-The-Geek commented on src/main/resources/blockbot-discord.toml
> +# Comma separated list of the role ID's allowed to use the command
Could this may be rephrased too?
```suggestion
# Comma separated list of the role ID's allowed to use inline commands
```

2021-11-10 12:22 UTC, Tom-The-Geek commented on src/main/resources/blockbot-discord.toml
> +# Require administrator on discord to use console
```suggestion
# Require administrator permissions on discord to use console
```

2021-11-10 13:47 UTC, Tom-The-Geek approved these changes

2022-11-13 20:56 UTC, NoComment1105 approved these changes

2022-11-13 20:59 UTC, PotatoPresident approved these changes

2022-12-29 12:16 UTC, he3als approved these changes

2023-05-21 17:56 UTC, closed without merging